export const COMPANY = {
  name:      "ZedroLabs",
  domain:    "zedrolabs.io",
  tagline:   "Software Development · Web3 · Virtual Assistants",
  email:     "info@zedrolabs.io",
  sales:     "sales@zedrolabs.io",
  phone:     "+92 332 6551460",
  whatsapp:  "+92 332 6551460",
  founded:   "2016",
};

export const STATS = [
  { num: 150, suffix: "+", label: "Projects Delivered",    icon: "🚀" },
  { num: 45,  suffix: "+", label: "Expert Engineers",       icon: "👥" },
  { num: 8,   suffix: "+", label: "Years Experience",       icon: "📅" },
  { num: 98,  suffix: "%", label: "Client Satisfaction",    icon: "⭐" },
  { num: 3,   suffix: "",  label: "Continents Served",      icon: "🌍" },
  { num: 50,  suffix: "M+",label: "Revenue Enabled ($)",   icon: "💰" },
];

export const MARQUEE_ITEMS = [
  "Custom Software", "Web3 & Blockchain",
  "Virtual Assistants", "Staff Augmentation",
];

export const CORE_SERVICES = [
  {
    icon: "💻",
    title: "Custom Software",
    short: "Web & Desktop Apps",
    desc: "Full-cycle development of enterprise web apps, SaaS platforms, and desktop software built for scale.",
    markets: ["B2B", "B2C", "B2G"],
    slug: "custom-software",
    color: "from-red-900/30 to-transparent",
    featured: false,
  },
  {
    icon: "⛓️",
    title: "Web3 & Blockchain",
    short: "DeFi · NFT · Smart Contracts",
    desc: "End-to-end blockchain development: DeFi protocols, NFT platforms, DAO governance, and enterprise blockchain.",
    markets: ["B2B", "Web3"],
    slug: "web3",
    color: "from-purple-900/30 to-transparent",
    featured: true,
    highlight: "🔥 High Demand",
  },
  {
    icon: "🤝",
    title: "Virtual Assistants",
    short: "Remote Professional Support",
    desc: "Dedicated VAs for admin, customer support, data entry, scheduling, social media, and executive assistance.",
    markets: ["B2B", "B2C"],
    slug: "virtual-assistants",
    color: "from-amber-900/25 to-transparent",
    featured: true,
    highlight: "From $320/mo",
  },
  {
    icon: "👥",
    title: "Dedicated Dev Teams",
    short: "Staff Augmentation",
    desc: "Pre-vetted, full-time engineers integrated directly into your team. From $640/month.",
    markets: ["B2B", "B2G"],
    slug: "dedicated-teams",
    color: "from-orange-900/25 to-transparent",
    featured: false,
    highlight: "From $640/mo",
  },
];

export const WEB3_SERVICES = [
  { icon: "📜", title: "Smart Contract Development", desc: "Solidity, Rust, and Cairo contracts: audited, gas-optimized, and production-ready." },
  { icon: "🏦", title: "DeFi Protocol Development", desc: "AMMs, lending protocols, yield optimizers, staking platforms, and liquidity pools." },
  { icon: "🖼️", title: "NFT Platforms & Marketplaces", desc: "Custom NFT minting, marketplaces, royalty systems, and fractional ownership." },
  { icon: "🏛️", title: "DAO & Governance Systems", desc: "On-chain governance, voting mechanisms, treasury management, and token economics." },
  { icon: "🔗", title: "Cross-Chain Bridges", desc: "Interoperability solutions, wrapped tokens, and cross-chain messaging protocols." },
  { icon: "🎮", title: "Web3 Gaming & Metaverse", desc: "Play-to-earn mechanics, in-game economies, virtual land, and metaverse integrations." },
  { icon: "🏢", title: "Enterprise Blockchain", desc: "Supply chain tracking, document authentication, and private blockchain deployments." },
  { icon: "🔐", title: "Security Audits", desc: "Comprehensive smart contract security audits, vulnerability assessments, and formal verification." },
];

export const MEDICAL_BILLING_SERVICES = [
  { icon: "📋", title: "Medical Billing & Coding", desc: "ICD-10, CPT, and HCPCS coding expertise across all specialties with 98%+ accuracy." },
  { icon: "💊", title: "Revenue Cycle Management", desc: "End-to-end RCM: eligibility verification, claim submission, payment posting, and AR follow-up." },
  { icon: "🔄", title: "Denial Management", desc: "Systematic denial analysis, appeal filing, and root-cause resolution to maximize collections." },
  { icon: "🏥", title: "EHR/EMR Integration", desc: "Seamless integration with Epic, Cerner, Athena, DrChrono, and 30+ EMR systems." },
  { icon: "📊", title: "Analytics & Reporting", desc: "Custom financial dashboards, payer analysis, KPI tracking, and collection forecasting." },
  { icon: "🔒", title: "HIPAA-Compliant Software", desc: "Custom healthcare software with end-to-end encryption, audit trails, and HIPAA compliance." },
  { icon: "⚡", title: "Claims Scrubbing & EDI", desc: "Automated claims scrubbing, EDI 837/835 processing, and real-time eligibility verification." },
  { icon: "📞", title: "Patient Collections", desc: "Compassionate patient billing, payment plans, and collection optimization strategies." },
];

export const VA_SERVICES = [
  { icon: "📅", title: "Executive VAs", desc: "Calendar management, travel booking, correspondence, and executive-level admin support." },
  { icon: "💬", title: "Customer Support VAs", desc: "Live chat, email support, ticket management, and CRM maintenance across time zones." },
  { icon: "📊", title: "Data Entry & Research", desc: "Web research, data collection, database management, and market intelligence gathering." },
  { icon: "📱", title: "Social Media VAs", desc: "Content scheduling, community management, DM handling, and analytics reporting." },
  { icon: "📝", title: "Content & Copywriting VAs", desc: "Blog writing, product descriptions, email campaigns, and SEO-optimized content." },
  { icon: "🛒", title: "E-Commerce VAs", desc: "Order processing, inventory management, supplier coordination, and listing optimization." },
  { icon: "💰", title: "Bookkeeping VAs", desc: "QuickBooks/Xero management, invoicing, expense tracking, and financial reporting." },
  { icon: "🎨", title: "Design & Creative VAs", desc: "Canva designs, social graphics, presentation creation, and basic video editing." },
];

export const VA_PRICING = [
  {
    name: "Part-Time VA",
    hours: "20 hrs/week",
    price: 320,
    period: "month",
    features: ["1 dedicated VA", "Any role/specialty", "Email + chat communication", "Weekly reports", "2-day replacement guarantee"],
    featured: false,
  },
  {
    name: "Full-Time VA",
    hours: "40 hrs/week",
    price: 640,
    period: "month",
    features: ["1 dedicated full-time VA", "Any role/specialty", "All communication channels", "Daily reports & standups", "24hr replacement guarantee", "Free 1-week trial"],
    featured: true,
    badge: "Most Popular",
  },
  {
    name: "VA Team",
    hours: "Multiple VAs",
    price: 1760,
    period: "month",
    features: ["3 dedicated VAs", "Mixed specialties", "Team lead included", "Priority support", "Same-day replacement", "Free 1-week trial", "Dedicated account manager"],
    featured: false,
  },
];

export const DEV_PRICING = [
  {
    name: "Starter",
    price: 640,
    role: "Junior Devs, QA, Basic Roles",
    features: [
      "Junior front-end / back-end devs",
      "Manual & automated QA testers",
      "160–180 hrs/month",
      "Daily standups",
      "Weekly progress reports",
      "Managed onboarding",
    ],
    featured: false,
  },
  {
    name: "Standard",
    price: 960,
    role: "Mid-Level Full-Stack, Mobile, DevOps",
    features: [
      "Mid-level full-stack developers",
      "iOS & Android mobile engineers",
      "CI/CD & DevOps engineers",
      "UI/UX designers",
      "All Starter features",
      "Agile sprint integration",
    ],
    featured: true,
    badge: "Most Popular",
  },
  {
    name: "Premium",
    price: 1440,
    role: "Senior Engineers, AI/ML, Architects",
    features: [
      "Senior software architects",
      "AI/ML & data scientists",
      "Blockchain / Web3 specialists",
      "Cloud infrastructure leads",
      "All Standard features",
      "Code review & tech leadership",
    ],
    featured: false,
  },
];

export const PORTFOLIO_PROJECTS = [
  {
    title: "Invoice Control",
    desc: "Built and operated in-house by ZedroLabs. Branded invoice creation and payment tracking for freelancers and startup founders, free to start, no spreadsheet required.",
    tech: ["SaaS", "In-House Product"],
    market: "B2B",
    emoji: "🧾",
    gradient: "from-red-950 via-rose-950 to-[#080c14]",
    stats: "Built & operated by ZedroLabs",
    link: "https://invoice.zedrolabs.io",
    image: "/portfolio/invoice-control.jpg",
  },
  {
    title: "Hajwari Jewellers",
    desc: "Shopify storefront for a handcrafted fine-jewellery brand: bridal sets, bangles, and custom pieces with premium packaging for the South Asian bridal market.",
    tech: ["Shopify", "Liquid", "E-Commerce"],
    market: "B2C",
    emoji: "💍",
    gradient: "from-amber-950 via-yellow-950 to-[#080c14]",
    stats: "Bridal & fine jewellery · Shopify",
    link: "https://hajwarijewellers.com/",
    image: "/portfolio/hajwari-jewellers.jpg",
  },
  {
    title: "Bloomen",
    desc: "Same-day flower delivery platform for the Greater Toronto Area: full catalog, subscriptions, and dedicated wedding/event floral services.",
    tech: ["E-Commerce", "Web Design"],
    market: "B2C",
    emoji: "🌸",
    gradient: "from-pink-950 via-rose-950 to-[#080c14]",
    stats: "280,000+ bouquets delivered",
    link: "https://bloomen.ca/",
    image: "/portfolio/bloomen.jpg",
  },
  {
    title: "NOVA Revenue Solutions",
    desc: "Revenue cycle management site for a US healthcare billing company: claims, credentialing, denial management, and EHR integrations across major systems.",
    tech: ["RCM", "Healthcare IT", "Web Design"],
    market: "B2B",
    emoji: "🏥",
    gradient: "from-emerald-950 via-teal-950 to-[#080c14]",
    stats: "Multi-state RCM & credentialing",
    link: "https://novarevenuesolution.com/",
    image: "/portfolio/nova-revenue-solutions.jpg",
  },
  {
    title: "Psychological Therapy Associates",
    desc: "Practice website for a Kansas-based therapy clinic: service pages, therapist bios, and an online client portal for booking.",
    tech: ["Web Design", "Healthcare"],
    market: "B2C",
    emoji: "🧠",
    gradient: "from-sky-950 via-blue-950 to-[#080c14]",
    stats: "EMDR, CBT & trauma-focused care",
    link: "https://www.psychtherapyassoc.com/",
    image: "/portfolio/psych-therapy-associates.jpg",
  },
  {
    title: "Planetize Packaging",
    desc: "E-commerce site for a Toronto-area eco-friendly packaging supplier: compostable and recyclable takeout packaging for restaurants and cafés.",
    tech: ["E-Commerce", "Web Design"],
    market: "B2B",
    emoji: "📦",
    gradient: "from-green-950 via-lime-950 to-[#080c14]",
    stats: "Sustainable food-service packaging",
    link: "https://planetizepackaging.ca/",
    image: "/portfolio/planetize-packaging.jpg",
  },
  {
    title: "The Altitude Marketing",
    desc: "Agency site for a Liverpool-based digital marketing firm: SEO, PPC, and web design services for UK brands.",
    tech: ["Web Design", "Branding"],
    market: "B2B",
    emoji: "📈",
    gradient: "from-orange-950 via-red-950 to-[#080c14]",
    stats: "10+ years · UK-wide clients",
    link: "https://thealtitudemarketing.co.uk/",
    image: "/portfolio/the-altitude-marketing.jpg",
  },
  {
    title: "The Notary Guy",
    desc: "Local service website for a Canadian mobile notary business: service area, booking, and pricing information.",
    tech: ["Web Design"],
    market: "B2C",
    emoji: "📝",
    gradient: "from-slate-950 via-gray-950 to-[#080c14]",
    stats: "Mobile notary services · Canada",
    link: "https://thenotaryguy.ca/",
    image: "/portfolio/the-notary-guy.jpg",
  },
  {
    title: "The Balanced Teacherpreneur",
    desc: "Coaching & community platform helping educators build businesses outside the classroom: courses, memberships, and a mentorship funnel.",
    tech: ["Web Design", "E-Commerce"],
    market: "B2C",
    emoji: "🍎",
    gradient: "from-orange-950 via-amber-950 to-[#080c14]",
    stats: "Courses, coaching & community",
    link: "https://www.balancedteacherpreneur.com/",
    image: "/portfolio/balanced-teacherpreneur.jpg",
  },
  {
    title: "Mysteek Naturals",
    desc: "Shopify store for a clean, temporary hair-color brand: product bundles, a shade-matching quiz, and a tiered creator partnership program.",
    tech: ["Shopify", "E-Commerce"],
    market: "B2C",
    emoji: "🎨",
    gradient: "from-fuchsia-950 via-purple-950 to-[#080c14]",
    stats: "Halal · Vegan · Kosher hair color",
    link: "https://mysteeknaturals.com",
    image: "/portfolio/mysteek-naturals.jpg",
  },
  {
    title: "Indie Dream Lab",
    desc: "Studio site for a mobile game development house building Unity-based, skill-based real-money games: portfolio, services, and discovery-call booking.",
    tech: ["Web Design", "Unity"],
    market: "B2B",
    emoji: "🎮",
    gradient: "from-indigo-950 via-violet-950 to-[#080c14]",
    stats: "30+ shipped titles · 2M+ players",
    link: "https://indiedreamlab.com/",
    image: "/portfolio/indie-dream-lab.jpg",
  },
  {
    title: "GemPay",
    desc: "Marketing site for a crypto payment processor: merchants accept 50+ cryptocurrencies and settle directly to cash, non-custodially.",
    tech: ["Web3", "Fintech", "Web Design"],
    market: "Web3",
    emoji: "💎",
    gradient: "from-cyan-950 via-blue-950 to-[#080c14]",
    stats: "50+ cryptocurrencies accepted",
    link: "https://gempay.io/",
    image: "/portfolio/gempay.jpg",
  },
  {
    title: "RS Coin",
    desc: "Dual-chain credential platform: an ERC-20 governance token on Ethereum (RS-CORE) paired with an SPL execution token on Solana (RS-FLOW), with tiered access NFTs.",
    tech: ["Solidity", "Solana", "Web3"],
    market: "Web3",
    emoji: "⛓️",
    gradient: "from-purple-950 via-indigo-950 to-[#080c14]",
    stats: "Dual-chain · Ethereum + Solana",
    link: "https://rs-coin-deployment.vercel.app/",
    image: "/portfolio/rs-coin.jpg",
  },
  {
    title: "Mintsy",
    desc: "Token launchpad platform for the memecoin market: create, launch, and trade tokens.",
    tech: ["Web3", "Solana"],
    market: "Web3",
    emoji: "🪙",
    gradient: "from-orange-950 via-amber-950 to-[#080c14]",
    stats: "Token launchpad",
    link: "https://mintsy.fun/",
  },
  {
    title: "MintsyPlus",
    desc: "Analytics and screener tool for tokens launched on Mintsy: live pricing, volume, market cap, and liquidity tracking.",
    tech: ["Web3", "Solana", "Analytics"],
    market: "Web3",
    emoji: "📊",
    gradient: "from-amber-950 via-yellow-950 to-[#080c14]",
    stats: "Real-time token analytics",
    link: "https://mintsy.plus/",
    image: "/portfolio/mintsy-plus.jpg",
  },
  {
    title: "UCURS",
    desc: "E-commerce platform for entrepreneurs: build a storefront, list products on a shared marketplace, and manage orders without hiring a developer.",
    tech: ["SaaS", "E-Commerce", "Web Design"],
    market: "B2B",
    emoji: "🛍️",
    gradient: "from-orange-950 via-red-950 to-[#080c14]",
    stats: "15-day free trial",
    link: "https://www.ucurs.com/",
    image: "/portfolio/ucurs.jpg",
  },
  {
    title: "Blast Wheels",
    desc: "Play-to-earn NFT racing game on the Sui blockchain: live multiplayer races, collectible cars, and a $WHEELS token marketplace.",
    tech: ["Web3", "Sui", "Gaming"],
    market: "Web3",
    emoji: "🏎️",
    gradient: "from-orange-950 via-amber-950 to-[#080c14]",
    stats: "Play-to-earn racing on Sui",
    link: "https://blast-wheels.com/",
    image: "/portfolio/blast-wheels.jpg",
  },
];

/* Actively in development, not yet public/launched — shown as an exclusive preview, not a finished case study. */
export const CURRENT_PROJECTS = [
  {
    title: "Schnitzy Haus",
    desc: "Brand and ordering site for a schnitzel-focused food brand, currently in build.",
    tech: ["Web Design", "E-Commerce"],
    market: "B2C",
    emoji: "🍽️",
    gradient: "from-amber-950 via-orange-950 to-[#080c14]",
    link: null,
    image: null,
  },
  {
    title: "Kwik Fat Cut",
    desc: "Free education platform on Jamaican and Caribbean ancestral food wisdom, built around \"education before intervention.\" Based in Kingston, Jamaica.",
    tech: ["Web Design", "Content Platform"],
    market: "B2C",
    emoji: "🥗",
    gradient: "from-yellow-950 via-amber-950 to-[#080c14]",
    link: "https://kwikfatcut.com/",
    image: "/portfolio/kwikfatcut.jpg",
  },
  {
    title: "Multi Brand Invoice",
    desc: "Next iteration of Invoice Control: one account, multiple branded businesses, each with its own invoice numbering and branding.",
    tech: ["SaaS", "In-House Product"],
    market: "B2B",
    emoji: "🧾",
    gradient: "from-red-950 via-rose-950 to-[#080c14]",
    link: null,
    image: null,
  },
  {
    title: "NFT Marketplace",
    desc: "In-house NFT marketplace build: minting, listings, and trading infrastructure.",
    tech: ["Web3", "Solidity"],
    market: "Web3",
    emoji: "🖼️",
    gradient: "from-purple-950 via-fuchsia-950 to-[#080c14]",
    link: null,
    image: null,
  },
  {
    title: "Liquidity Manager",
    desc: "In-house DeFi tool for automated liquidity position management across pools.",
    tech: ["Web3", "DeFi"],
    market: "Web3",
    emoji: "💧",
    gradient: "from-cyan-950 via-blue-950 to-[#080c14]",
    link: null,
    image: null,
  },
];

export const TESTIMONIALS = [
  {
    name: "Marcus Chen",
    role: "CTO, FinTech Startup, San Francisco",
    avatar: "MC",
    rating: 5,
    text: "ZedroLabs delivered our DeFi protocol 3 weeks early and under budget. The smart contract audit they ran caught 2 critical vulnerabilities before launch. These guys are absolute pros.",
  },
  {
    name: "Dr. Sarah Williams",
    role: "Practice Administrator, Houston Medical Group",
    avatar: "SW",
    rating: 5,
    text: "Our collections went up 34% after switching to ZedroLabs for RCM. Their medical billing team knows the industry inside-out and their denial management is phenomenal.",
  },
  {
    name: "Alex Rodriguez",
    role: "CEO, E-Commerce Brand, Miami",
    avatar: "AR",
    rating: 5,
    text: "The virtual assistant they matched me with is incredible. She manages my entire inbox, social media, and customer support. It's like having a superstar employee for a fraction of the cost.",
  },
  {
    name: "James O'Brien",
    role: "VP Engineering, Enterprise SaaS, London",
    avatar: "JO",
    rating: 5,
    text: "We've used ZedroLabs for dedicated engineering teams for 2 years. Consistently excellent talent, transparent communication, and the time zone overlap with UK hours is perfect.",
  },
];

export const TECH_STACK = {
  "Frontend":   ["React", "Next.js", "Vue.js", "Angular", "React Native", "Flutter"],
  "Backend":    ["Node.js", "Python", "Django", "FastAPI", "Go", "Java / Spring"],
  "Blockchain": ["Solidity", "Rust", "Hardhat", "Foundry", "Ethers.js", "Web3.js"],
  "Cloud":      ["AWS", "Azure", "GCP", "Kubernetes", "Docker", "Terraform"],
  "AI/ML":      ["TensorFlow", "PyTorch", "OpenAI API", "LangChain", "Hugging Face", "scikit-learn"],
  "Database":   ["PostgreSQL", "MongoDB", "Redis", "Supabase", "PlanetScale", "TimescaleDB"],
  "Healthcare": ["HL7 FHIR", "Epic API", "Athena", "DrChrono", "EDI 837/835", "HL7 v2"],
};

export const FAQS = [
  {
    q: "How quickly can you start a project?",
    a: "For dedicated teams and VAs, we can onboard resources within 3–7 business days. For custom projects, we begin with a discovery workshop and can start development within 1–2 weeks of kickoff.",
  },
  {
    q: "Are your smart contracts audited?",
    a: "All smart contracts we deploy go through internal security review. For production DeFi protocols, we partner with leading audit firms (Certik, Trail of Bits, etc.) or conduct full in-house audits.",
  },
  {
    q: "What's the minimum contract for VAs?",
    a: "We offer 1-month minimum commitments for Virtual Assistants, with a free 1-week trial on full-time packages. For dedicated dev teams, the minimum is 3 months.",
  },
  {
    q: "Do you sign NDAs before discussions?",
    a: "Always. We sign mutual NDAs before any technical discussions and ensure full IP transfer on project completion. Your ideas are safe with us.",
  },
  {
    q: "What time zone coverage do you offer?",
    a: "Our core team is PKT (UTC+5) but we offer flexible shift options for US EST/PST, UK GMT, and Gulf GST overlap. Most clients get 4–6 hours of daily overlap.",
  },
];

export const TEAM = [
  { name: "Muhammad Osama", role: "CEO & Founder", spec: "Full-Stack & Blockchain Engineering", emoji: "👨‍💼", linkedin: "#" },
  { name: "Aansa Khalid", role: "Co-Founder", spec: "Strategy & Operations", emoji: "👩‍💼", linkedin: "#" },
  { name: "Mahnoor", role: "Chief Designer", spec: "Product & UX Design", emoji: "🎨", linkedin: "#" },
  { name: "Ali Joyo", role: "Software Engineer", spec: "Full-Stack Development", emoji: "💻", linkedin: "#" },
  { name: "Subhan", role: "Project Manager", spec: "Delivery & Client Success", emoji: "🤝", linkedin: "#" },
];
